petshop/petshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
 path('admin/', admin.site.urls),
 path('', include('shop.urls', namespace='shop')),
]
if settings.DEBUG:
 urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

petshop/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'
urlpatterns = [
 path('', views.product_list, name='product_list'),
 path('<slug:category_slug>/', views.product_list,
 name='product_list_by_category'),
 path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

petshop/shop/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])

    def __str__(self):
            return self.name

class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

    def __str__(self):
        return self.name

petshop/shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product

# Create your views here.
def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'shop/product/list.html', {'category':category, 'categories':categories, 'products':products})

def product_detail(request, id, slug):
    categories = Category.objects.all()
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    return render(request, 'shop/product/detail.html', {'product':product, 'categories':categories})

petshop/shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}ЛАПКИ{% endblock %}</title>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link type="image/x-icon" rel="icon" href="static/img/cat.png">
        <style>
        .w3-sidebar a {font-family: "Roboto", sans-serif; overflow: hidden;}
        body,h1,h2,h3,h4,h5,h6,.w3-wide {font-family: "Montserrat", sans-serif;}
        .product-detail {text-align:justify;}
        .product-detail .price {color:#333; font-size:28px; font-weight:bold;}
        .product-detail img {width:40%; float:left; padding:0 20px 20px 0;}
        .product-detail h1 {margin-bottom:0;}
        .product-detail h2 {margin-top:10px;}
        </style>
    </head>

<body class="w3-content" style="max-width:1200px">

<nav class="w3-sidebar w3-bar-block w3-white w3-collapse w3-top" style="z-index:3;width:250px" id="mySidebar">
  <div class="w3-container w3-display-container w3-padding-16">
    <i onclick="w3_close()" class="fa fa-remove w3-hide-large w3-button w3-display-topright"></i>
      <h3> <a href="{% url "shop:product_list" %}" class="w3-wide"><b>ЛАПА</b></a></h3>
  </div>

  <div class="w3-padding-64 w3-large w3-text-grey" style="font-weight:bold">
    <div {% if not category %} class="w3-button w3-block w3-white w3-left-align"{% endif %}>
     <a href="{% url "shop:product_list" %}"class="w3-button w3-block w3-white w3-left-align">Все товары</a>

 {% for c in categories %}
    <a  href="{{ c.get_absolute_url }}" class="w3-button w3-block w3-white w3-left-align" id="myBtn">{{ c.name }}</a>
 {% endfor %}

<!--
    <a onclick="myAccFunc()" href="javascript:void(0)" class="w3-button w3-block w3-white w3-left-align" id="myBtn">
      Категория <i class="fa fa-caret-down"></i>
    </a>
    <div id="demoAcc" class="w3-bar-block w3-hide w3-padding-large w3-medium">
      <a href="#" class="w3-bar-item w3-button w3-light-grey"><i class="fa fa-caret-right w3-margin-right"></i>Подкатегория 1</a>
      <a href="#" class="w3-bar-item w3-button">Подкатегория 2</a>
      <a href="#" class="w3-bar-item w3-button">Подкатегория 3</a>
      <a href="#" class="w3-bar-item w3-button">Подкатегория 4</a>
    </div>
-->
    </div>
  </div>
</nav>

<!-- Top menu on small screens -->
<header class="w3-bar w3-top w3-hide-large w3-black w3-xlarge">
  <div class="w3-bar-item w3-padding-24 w3-wide">ЛАПА</div>
  <a href="javascript:void(0)" class="w3-bar-item w3-button w3-padding-24 w3-right" onclick="w3_open()"><i class="fa fa-bars"></i></a>
</header>

<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

<!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left:250px">

  <!-- Push down content on small screens -->
  <div class="w3-hide-large" style="margin-top:83px"></div>

  <!-- Top header -->
  <header class="w3-container w3-xlarge">
    <p class="w3-left">Зоомагазин</p>
    <p class="w3-right">
      <i class="fa fa-shopping-cart w3-margin-right"></i>
      <i class="fa fa-search"></i>
    </p>
  </header>


        <div id="content">
            {% block content %}{% endblock %}
        </div>

<script>
// Open and close sidebar
function w3_open() {
  document.getElementById("mySidebar").style.display = "block";
  document.getElementById("myOverlay").style.display = "block";
}

function w3_close() {
  document.getElementById("mySidebar").style.display = "none";
  document.getElementById("myOverlay").style.display = "none";
}
</script>
</body>
</html>

petshop/shop/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
    {{ product.name }}
{% endblock %}

{% block content %}
    <div class="product-detail">
        <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img\no_image.png' %}{% endif %}">
        <h1>{{ product.name }}</h1>
        <h2><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h2>
        <p class="price">{{ product.price }} Руб.</p>
        <div id="product-description">
            {{ product.description|linebreaks}}
        </div>
    </div>
{% endblock %}

petshop/shop/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    {%if category %}{{ category.name}}{% else %}Зоомагазин ЛАПКИ{% endif %}
{% endblock %}

{% block content %}
<!-- Image header -->
  <div class="w3-display-container w3-container">
    <img src="https://cdn.shopify.com/s/files/1/0344/6469/files/Screen_Shot_2017-03-02_at_3.19.41_PM_grande.png?v=1488486032" alt="Лапки" style="width:100%">
    <div class="w3-display-topleft w3-text-black" style="padding:24px 48px">
        <h1 class="w3-jumbo w3-hide-small" style="background-color:#d7d8d8; "><b>ПРЕМИАЛЬНЫЕ КОРМА</b></h1>

        <h1 class="w3-hide-small"><b>Новое поступление</b></h1>
        <p><a href="#jeans" class="w3-button w3-black w3-padding-large w3-large">КУПИТЬ</a></p>
    </div>
  </div>

  <!-- Product grid -->
  <div class="w3-row">
  <h1>{% if category %}{{category.name}}{% else %}Товары{% endif %}</h1>
  {% for product in products %}
    <div class="w3-col l3 s6">
      <div class="w3-container">
          <a href="{{ product.get_absolute_url }}">
            <img src="{% if product.image %}{{product.image.url}}{% else %}{% static 'img/no_image.png' %}{% endif %}" style="width:100%">
          </a>
          <p>
          <a href="{{ product.get_absolute_url }}">{{ product.name|truncatechars:60}}</a>
          <br>
              <b>{{ product.price }} Руб</b>
          </p>
      </div>
    </div>
  {% endfor %}
  </div>

{% endblock %}